name: Build and Deploy
on:
  push:
    branches:
      - "master"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: Setup Dependencies
        run: |
          uv --project scorer sync

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
          install-modules: |
            Math::Round
            YAML

      - name: Test Scoring
        run: |
          uv --project scorer run main -t tests input/config.yaml

      - name: Build Website
        run: |
          uv --project scorer run main -w build input/config.yaml

      - name: Upload Website
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
